# Generated by Django 4.2.27 on 2026-03-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=100)),
                ('data_carregamento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sequencial', models.PositiveIntegerField()),
                ('quantidade_sacos', models.PositiveIntegerField(default=84)),
                ('peso_saco_kg', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes', to='pellet.container')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_lote', models.CharField(max_length=50, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('quantidade_containers_prevista', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('PRODUZINDO', 'Em Produção'), ('FINALIZADO', 'Finalizado')], default='PLANEJADO', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='pellet.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='pellet.lote'),
        ),
    ]
