# Generated by Django 6.0.1 on 2026-01-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pellet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('quantidade', models.ImageField(upload_to='')),
                ('turno', models.CharField(choices=[('1', '1 - Turno'), ('2', '2 - Turno'), ('3', '3 - Turno')], max_length=2)),
            ],
        ),
    ]
